apiVersion: v1
kind: Service
metadata:
  name: {{ include "wyoming-kanitts.fullname" . }}
  labels:
    {{- include "wyoming-kanitts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: wyoming
    protocol: TCP
    name: wyoming
  selector:
    {{- include "wyoming-kanitts.selectorLabels" . | nindent 4 }}
