apiVersion: v2
name: wyoming-piper
description: A Helm chart for Wyoming Piper text-to-speech service
type: application
version: 0.7.1
appVersion: "2.1.1"
keywords:
  - piper
  - wyoming
  - text-to-speech
  - tts
  - home-assistant
  - rhasspy
maintainers:
  - name: mikesmitty
sources:
  - https://github.com/rhasspy/wyoming-piper
  - https://github.com/rhasspy/piper
